#ifndef REGOLITH_TYPES_H
#define REGOLITH_TYPES_H

using PlayerID = uint32_t;
using EntityInstanceID = uint32_t ;
using EntityID = uint32_t;
using ZoneID = uint32_t;
using PropertyID_t = uint32_t;
using Port = uint16_t;

enum class rStatusCode{
    SUCCESS,
    REGISTER_ZONE_FAILED,
    UNREGISTER_ZONE_FAILED,
    ZONE_IS_INSTANTIATED,
    ZONE_IS_NOT_INSTANTIATED,
    LOAD_ZONE_FAILED,
    UNLOAD_ZONE_FAILED,
    INSTANTIATE_ZONE_START_FAILED,
    INSTANTIATE_ZONE_FINISH_FAILED,
    UNINSTANTIATE_ZONE_FAILED,
    ZONE_WITH_PROVIDED_NAME_NOT_FOUND,
    ZONE_WITH_PROVIDED_ID_NOT_FOUND,
    NULL_ZONE_PROVIDED,
    ENGINEHOOK_ERR
};

enum class rMessageType : uint8_t {
    NONE,
    ASSIGN_PLAYER_ID,
    LOAD_ZONE_REQUEST,
    LOAD_ZONE_FAILED_INVALID_ID,
    LOAD_ZONE_ACKNOWLEDGE,
    LOAD_ZONE_COMPLETE,
    PLAYER_UNLOADED_ZONE,
    CREATE_ENTITY_REQUEST,
    CREATE_ENTITY_ACKNOWLEDGE,
    ALLOCATE_INCOMING_PLAYER,
    ALLOCATE_INCOMING_PLAYER_ACK
};


#endif //REGOLITH_TYPES_H
